added inspiral and merged triggers options. Also improved time.

diff --git a/bin/pycbc_copy_output_map b/bin/pycbc_copy_output_map
--- a/bin/pycbc_copy_output_map
+++ b/bin/pycbc_copy_output_map
@@ -2,10 +2,13 @@
 
 INPUT_FILE=""
 OUTPUT_FILE=""
+KEEP_ALL=1
+FILE_REGEX=()
+CHECK_FILES=0
 
 CMD_OPTS=$(getopt \
-    -o hi:o: \
-    -l help,input-file:,output-file: \
+    -o hi:o:Imc \
+    -l help,input-file:,output-file:,inspirals,merged-triggers,check-files \
     -n pycbc_copy_output_map \
     -- "$@")
 
@@ -18,11 +21,16 @@ do
 	    echo "usage: pycbc_copy_output_map [-h] input_map output_map [optional arguments]"
 	    echo
 	    echo "required arguments:"
-	    echo "  -i, --input-file      the .map file that will be copied from"
-	    echo "  -o, --output-file     the name of the output file to be created"
+	    echo "  -i, --input-file        the .map file that will be copied from"
+	    echo "  -o, --output-file       the name of the output file to be created"
 	    echo
 	    echo "optional arguments:"
-	    echo "  -h, --help            show this help message and exit"
+	    echo "  -h, --help              show this help message and exit"
+	    echo "  -I, --inspirals         if given all entries will no longer be copied,"
+	    echo "                            only inspirals and any other specified file types."
+	    echo "  -m, --merged-triggers   if given all entries will no longer be copied,"
+	    echo "                            only merged-triggers and any other specified file types."
+	    echo "  -c, --check-files       check if the files exist with non-zero size before copying."
 	    echo
 	    exit 0 ;;
 	-i|--input-file)
@@ -31,6 +39,17 @@ do
 	-o|--output-file)
 	    OUTPUT_FILE=$(readlink -f "$2")
 	    shift 2 ;;
+	-I|--inspirals)
+	    KEEP_ALL=0
+	    FILE_REGEX+=("1-INSPIRAL")
+	    shift 1 ;;
+	-m|--merged-triggers)
+	    KEEP_ALL=0
+	    FILE_REGEX+=("1-HDF_TRIGGER_MERGE")
+	    shift 1 ;;
+	-c|--check-files)
+	    CHECK_FILES=1
+	    shift 1 ;;
 	--)
 	    break ;;
     esac
@@ -65,21 +84,57 @@ then
 fi
 
 touch "$OUTPUT_FILE"
+ERROR=""
+MESSAGE=""
 
 while read -r LINE
 do
-    read -ra ARRAY <<< "$LINE"
+    KEEP_FILE=0
+    ARRAY=($LINE)
     if (( ${#ARRAY[@]} != 3 ))
     then
-	echo "A line contained ${#ARRAY[@]} space seperated entries."
-	echo "A map file should contain 3 per line"
-	exit 1
-    elif [[ "${ARRAY[1]}" == *.dax ]] || [[ "${ARRAY[1]}" == *.dax.map ]] || [[ "${ARRAY[1]}" == *.tc.txt ]]
+	ERROR="${ERROR}A line contained ${#ARRAY[@]} space seperated entries.\n" 
+	ERROR="${ERROR}A map file should contain 3 per line.\n"
+	break
+    elif [[ "${ARRAY[1]}" =~ \.dax$ ]] || [[ "${ARRAY[1]}" =~ \.dax\.map$ ]] || [[ "${ARRAY[1]}" =~ \.tc\.txt$ ]]
     then
-	echo "Skipping subdax file: ${ARRAY[1]}"
+	MESSAGE="${MESSAGE}Skipping subdax file: ${ARRAY[1]}\n"
+	continue
+    elif (( KEEP_ALL == 1 ))
+    then
+	KEEP_FILE=1
+    fi
+
+    for REGEX in ${FILE_REGEX[@]}
+    do
+	if [[ "${ARRAY[0]}" =~ $REGEX ]]
+	then
+	    KEEP_FILE=1
+	    break
+	fi
+    done
+
+    if (( KEEP_FILE != 1 ))
+    then
+	continue
+    elif (( CHECK_FILES == 0 ))
+    then
+	echo "$LINE"
 	continue
     elif [ -s "${ARRAY[1]}" ]
     then
-	echo "$LINE" >> "$OUTPUT_FILE"
+	echo "$LINE"
     fi
-done < "$INPUT_FILE"
+
+done < "$INPUT_FILE" >> $OUTPUT_FILE
+
+if [ "x${MESSAGE}" != "x" ]
+then
+    printf "$MESSAGE"
+fi
+
+if [ "x${ERROR}" != "x" ]
+then
+    printf "$ERROR"
+    exit 1
+fi
