added command line argument parsing to pegasus_submit_dax scripts

diff --git a/bin/pycbc_submit_dax b/bin/pycbc_submit_dax
--- a/bin/pycbc_submit_dax
+++ b/bin/pycbc_submit_dax
@@ -1,4 +1,49 @@
 #!/bin/bash
+
+DAX_FILE=""
+CACHE_FILE=""
+
+GETOPT_CMD=`getopt -o d:c:h --long dax:,cache-file:,help -n 'pycbc_submit_dax' -- "$@"`
+eval set -- "$GETOPT_CMD"
+
+while true ; do
+  case "$1" in
+    -d|--dax)
+      case "$2" in
+        "") shift 2 ;;
+        *) DAX_FILE=$2 ; shift 2 ;;
+      esac ;;
+    -c|--cache-file)
+      case "$2" in
+        "") shift 2 ;;
+        *) CACHE_FILE=$2 ; shift 2 ;;
+      esac ;;
+    -h|--help)
+      echo "usage: pycbc_submit_dax [-h]"
+      echo "                        --dax DAX"
+      echo "                        [--cache-file FILE]"
+      echo
+      echo "required arguments:"
+      echo "  -d, --dax DAX           name of the dax file to plan"
+      echo
+      echo "optional arguments:"
+      echo "  -h, --help              show this help message and exit"
+      echo "  -c, --cache-file FILE   replica cache file for data reuse"
+      echo
+      echo "If the environment variable TMPDIR is set then this is prepended to the "
+      echo "path to the temporary workflow execte directory passed to pegasus-plan."
+      echo
+      exit 0 ;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; exit 1 ;;
+  esac
+done
+
+if [ "x$DAX_FILE" == "x" ]; then
+  echo "Error: --dax must be specified. Use --help for options."
+   exit 1
+fi
+
 # Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
 set -e
 
@@ -17,7 +62,7 @@ if [ "x$1" == "x" ]; then
 fi
 
 #Make a directory for the submit files
-SUBMIT_DIR=`mktemp -d`
+SUBMIT_DIR=`mktemp -d pycbc-tmp.XXXXXXXXXX`
 
 #Make sure the directory is world readable
 chmod 755 $SUBMIT_DIR
@@ -37,11 +82,11 @@ bash temp.sh > site-local-parsed.xml
 echo "Generating concrete workflow"
 touch _reuse.cache
 
-if [ "x$2" == "x--cache" ]; then
-  cp $3 _reuse.cache
-  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $1 --sites local -o local --dir $SUBMIT_DIR --cleanup inplace --cache _reuse.cache --relative-submit-dir work --cluster label --submit
+if [ "x$CACHE_FILE" == "x" ]; then
+  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $DAX_FILE --sites local -o local --dir $SUBMIT_DIR --cleanup inplace --relative-submit-dir work --cluster label --submit 
 else
-  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $1 --sites local -o local --dir $SUBMIT_DIR --cleanup inplace --relative-submit-dir work --cluster label --submit 
+  cp $CACHE_FILE _reuse.cache
+  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $DAX_FILE --sites local -o local --dir $SUBMIT_DIR --cleanup inplace --cache _reuse.cache --relative-submit-dir work --cluster label --submit
 fi
 
 ln -s $SUBMIT_DIR submitdir
