allow multiple cache files

diff --git a/bin/pycbc_submit_dax b/bin/pycbc_submit_dax
--- a/bin/pycbc_submit_dax
+++ b/bin/pycbc_submit_dax
@@ -11,7 +11,7 @@ exec > >(tee submit.log)
 exec 2>&1
 
 DAX_FILE=""
-CACHE_FILE=""
+CACHE_FILE=0
 LOCAL_PEGASUS_DIR=""
 ACCOUNTING_GROUP=""
 NO_ACCOUNTING_GROUP=0
@@ -24,6 +24,8 @@ NO_CREATE_PROXY=0
 SUBMIT_DAX="--submit"
 
 echo "# Properties set on command line" > extra-properties.conf
+rm -f _reuse.cache
+touch _reuse.cache
 
 GETOPT_CMD=`getopt -o d:c:g:a:p:P:s:S:t:Fknl:h --long dax:,cache-file:,local-gsiftp-server:,accounting-group:,pegasus-properties:,append-pegasus-property:,execution-sites:,staging-sites:,transformation-catalog:,force-no-accounting-group,no-create-proxy,no-submit,local-dir:,help -n 'pycbc_submit_dax' -- "$@"`
 eval set -- "$GETOPT_CMD"
@@ -38,7 +40,14 @@ while true ; do
     -c|--cache-file)
       case "$2" in
         "") shift 2 ;;
-        *) CACHE_FILE=$2 ; shift 2 ;;
+        *) CACHE_FILE=1
+           if [ -e $2 ] ; then 
+             cat $2 >> _reuse.cach
+             else
+               echo "Error: cache file $2 not found"
+               exit 1
+             fi
+           shift 2 ;;
       esac ;;
     -g|--local-gsiftp-server)
       case "$2" in
@@ -238,7 +247,6 @@ bash site-catalog.sh > site-catalog.xml
 
 # Plan the workflow
 echo "Generating concrete workflow"
-touch _reuse.cache
 
 # cache the pegasus config
 if [ -z ${PEGASUS_PROPERTIES} ] ; then
@@ -258,10 +266,9 @@ fi
 echo >> pegasus-properties.conf
 cat extra-properties.conf >> pegasus-properties.conf
 
-if [ "x$CACHE_FILE" == "x" ]; then
+if [ $CACHE_FILE == 0 ]; then
   pegasus-plan --conf ./pegasus-properties.conf -d $DAX_FILE --sites $SITE_LIST $STAGING_SITES -o local --dir $SUBMIT_DIR --cleanup inplace --relative-submit-dir work --cluster label $SUBMIT_DAX 
 else
-  cp $CACHE_FILE _reuse.cache
   pegasus-plan --conf ./pegasus-properties.conf -d $DAX_FILE --sites $SITE_LIST $STAGING_SITES -o local --dir $SUBMIT_DIR --cleanup inplace --cache _reuse.cache --relative-submit-dir work --cluster label $SUBMIT_DAX
 fi
 
