added proper command line option parsing to planning script

diff --git a/bin/pycbc_basic_pegasus_plan b/bin/pycbc_basic_pegasus_plan
--- a/bin/pycbc_basic_pegasus_plan
+++ b/bin/pycbc_basic_pegasus_plan
@@ -1,12 +1,57 @@
 #!/bin/bash
-# Check I have two arguments supplied
-if [ "x$1" == "x" ]; then
-  echo "I take two arguments, the name of the dax file and the logpath. None supplied."
+
+DAX_FILE=""
+LOG_PATH=""
+CACHE_FILE=""
+
+GETOPT_CMD=`getopt -o d:l:c:h --long dax:,log-path:,cache-file:,help -n 'pycbc_basic_pegasus_plan' -- "$@"`
+eval set -- "$GETOPT_CMD"
+
+while true ; do
+  case "$1" in
+    -d|--dax)
+      case "$2" in
+        "") shift 2 ;;
+        *) DAX_FILE=$2 ; shift 2 ;;
+      esac ;;
+    -l|--log-path)
+      case "$2" in
+        "") shift 2 ;;
+        *) LOG_PATH=$2 ; shift 2 ;;
+      esac ;;
+    -c|--cache-file)
+      case "$2" in
+        "") shift 2 ;;
+        *) CACHE_FILE=$2 ; shift 2 ;;
+      esac ;;
+    -h|--help)
+      echo "usage: pycbc_basic_pegasus_plan [-h]"
+      echo "                                --dax DAX"
+      echo "                                --log-path LOG"
+      echo "                                [--cache-file FILE]"
+      echo
+      echo "required arguments:"
+      echo "  -d, --dax DAX           name of the dax file to plan"
+      echo "  -l, --log-path LOG      log directory where the excutable workflow is"
+      echo "                             generated"
+      echo
+      echo "optional arguments:"
+      echo "  -h, --help              show this help message and exit"
+      echo "  -c, --cache-file FILE   comma separated list of replica cache files"
+      echo
+      exit 0 ;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; exit 1 ;;
+  esac
+done
+
+if [ "x$DAX_FILE" == "x" ]; then
+  echo "Error: --dax must be specified. Use --help for options."
   exit 1
 fi
 
-if [ "x$2" == "x" ]; then
-  echo "I take two arguments, the name of the dax file and the logpath. Only got one: $1"
+if [ "x$LOG_PATH" == "x" ]; then
+  echo "Error: --log-path must be specified. Use --help for options."
   exit 1
 fi
 
@@ -24,9 +69,9 @@ bash temp.sh > site-local-parsed.xml
 echo "Generating concrete workflow"
 touch _reuse.cache
 
-if [ "x$3" == "x--cache" ]; then
-  cp $4 _reuse.cache
-  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $1 --sites local -o local --dir $2 --cleanup inplace --cache $4 --cluster label,horizontal
+if [ "x$CACHE_FILE" != "x" ]; then
+  cp $CACHE_FILE _reuse.cache
+  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $DAX_FILE --sites local -o local --dir $LOG_PATH --cleanup inplace --cache $CACHE_FILE --cluster label,horizontal
 else
-  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $1 --sites local -o local --dir $2 --cleanup inplace --cluster label,horizontal
+  pegasus-plan --conf $PEG_DIR/basic_pegasus.conf -d $DAX_FILE --sites local -o local --dir $LOG_PATH --cleanup inplace --cluster label,horizontal
 fi
