force the user to have a valid proxy

diff --git a/bin/pycbc_submit_dax b/bin/pycbc_submit_dax
--- a/bin/pycbc_submit_dax
+++ b/bin/pycbc_submit_dax
@@ -240,7 +240,25 @@ if [ $NO_CREATE_PROXY == 0 ]; then
   done
   unset X509_USER_PROXY
   ligo-proxy-init $LIGO_USER_NAME || exit 1
+else
+  if [ ! -z ${X509_USER_PROXY} ] ; then
+    if [ -f ${X509_USER_PROXY} ] ; then
+      cp -a ${X509_USER_PROXY} /tmp/x509up_u`id -u`
+      unset X509_USER_PROXY
+    fi
+  fi
 fi
+
+#Check that the proxy is valid
+grid-proxy-info -exists
+RESULT=$?
+if [ ${RESULT} -eq 0 ] ; then
+  grid-proxy-info
+else
+  echo "Error: Could not find a valid grid proxy to submit workflow."
+  exit 1
+fi
+
 
 #Make a directory for the submit files
 SUBMIT_DIR=`mktemp --tmpdir=${LOCAL_PEGASUS_DIR} -d pycbc-tmp.XXXXXXXXXX`
@@ -387,7 +405,35 @@ chmod 755 debug
 echo pegasus-remove $SUBMIT_DIR/work > stop
 chmod 755 stop
 
-echo pegasus-run $SUBMIT_DIR/work > start
+echo > start << EOF
+#!/bin/bash
+
+if [ -f /tmp/x509up_u`id -u` ] ; then
+  unset X509_USER_PROXY
+else
+  if [ ! -z ${X509_USER_PROXY} ] ; then
+    if [ -f ${X509_USER_PROXY} ] ; then
+      cp -a ${X509_USER_PROXY} /tmp/x509up_u`id -u`
+      unset X509_USER_PROXY
+    fi
+  fi
+fi
+
+# Check that the proxy is valid
+grid-proxy-info -exists
+RESULT=$?
+if [ ${RESULT} -eq 0 ] ; then
+  grid-proxy-info
+else
+  echo "Error: Could not find a valid grid proxy to submit workflow."
+  exit 1
+fi
+
+EOF
+echo pegasus-run $SUBMIT_DIR/work >> start
+
+
+
 chmod 755 start
 
 # Copy planning information into workflow directory so it can be displayed on the results page
