allow the user to specify additional site templates

diff --git a/bin/pycbc_submit_dax b/bin/pycbc_submit_dax
--- a/bin/pycbc_submit_dax
+++ b/bin/pycbc_submit_dax
@@ -16,8 +16,9 @@ LOCAL_PEGASUS_DIR=""
 ACCOUNTING_GROUP=""
 NO_ACCOUNTING_GROUP=0
 PEGASUS_PROPERTIES=""
+SITE_LIST=""
 
-GETOPT_CMD=`getopt -o d:c:a:p:Fl:h --long dax:,cache-file:,accounting-group:,pegasus-properties:,force-no-accounting-group,local-dir:,help -n 'pycbc_submit_dax' -- "$@"`
+GETOPT_CMD=`getopt -o d:c:a:p:s:Fl:h --long dax:,cache-file:,accounting-group:,pegasus-properties:,execution-sites:,force-no-accounting-group,local-dir:,help -n 'pycbc_submit_dax' -- "$@"`
 eval set -- "$GETOPT_CMD"
 
 while true ; do
@@ -35,12 +36,17 @@ while true ; do
     -a|--accounting-group)
       case "$2" in
         "") shift 2 ;;
-        *) ACCOUNTING_GROUP=$2 ; shift 2 ;;
+        *) export ACCOUNTING_GROUP=$2 ; shift 2 ;;
       esac ;;
     -p|--pegasus-properties)
       case "$2" in
         "") shift 2 ;;
         *) PEGASUS_PROPERTIES=$2 ; shift 2 ;;
+      esac ;;
+    -s|--execution-sites)
+      case "$2" in
+        "") shift 2 ;;
+        *) SITE_LIST=$2 ; shift 2 ;;
       esac ;;
     -F|--force-no-accounting-group) NO_ACCOUNTING_GROUP=1 ; shift ;;
     -l|--local-dir)
@@ -67,7 +73,12 @@ while true ; do
       echo "  -F, --force-no-accounting-group submit without an accounting"
       echo "                               group. Will cause condor submission"
       echo "                               to fail on LIGO Data Grid clusters"
-      echo "  -l, --local-dir         Directory to put condor files under. "
+      echo "  -p, --pegasus-properties FILE use the specified file as"
+      echo "                               the pegasus properties file"
+      echo "  -s, --execution-sites A,B,C specify a comma separated list"
+      echo "                               of execution sites that will be"
+      echo "                               used in addition to the local site"
+      echo "  -l, --local-dir         Directory to put condor files under"
       echo
       echo "If the environment variable TMPDIR is set then this is prepended to the "
       echo "path to the temporary workflow execte directory passed to pegasus-plan."
@@ -113,26 +124,43 @@ chmod 755 $SUBMIT_DIR
 
 # find the site-local template directory
 PEG_DIR=`python -c 'from pycbc.workflow import PEGASUS_FILE_DIRECTORY;print PEGASUS_FILE_DIRECTORY'`
-SITE_TEMPLATE=$PEG_DIR/local-site-template.xml
-
-export ACCOUNTING_GROUP
-
-# Set up the site-local with the correct paths
-echo 'cat <<END_OF_TEXT' >  local-site.sh
-cat $SITE_TEMPLATE       >> local-site.sh
-echo 'END_OF_TEXT'       >> local-site.sh
 
 # Create the site catalog
+
+# add the local site
+if [[ -z $SITE_LIST ]] ; then
+  SITE_LIST="local"
+else
+  SITE_LIST="local,${SITE_LIST}"
+fi
+
+# create the site catalog template
+echo 'cat <<END_OF_TEXT' > site-catalog.sh
+
+if [[ -z ${PEGASUS_SITE_CATALOG_PATH} ]] ; then
+  PEGASUS_SITE_CATALOG_PATH=${PEG_DIR}
+fi
+
+IFS=',' ; read -ra SITE <<< "$SITE_LIST"
+for s in "${SITE[@]}"; do
+  SITE_TEMPLATE=$PEGASUS_SITE_CATALOG_PATH/${s}-site-template.xml
+  if [[ ! -f ${SITE_TEMPLATE} ]] ; then
+    echo "Error: Could not find site catalog template for site ${s}"
+    exit 1
+  else
+    cat $SITE_TEMPLATE >> site.sh
+  fi
+done
+
+echo 'END_OF_TEXT'       >> site.sh
+
+# write out the site catalog
 echo > site-catalog.xml <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">
 EOF
-
-# add the local site
-bash local-site.sh >> site-catalog.xml
-
-# close the site catalog xml
+bash site-catalog.sh >> site-catalog.xml
 echo >> site-catalog.xml <<EOF
 </sitecatalog>
 EOF
