fixes https://github.com/gwastro/pycbc/issues/2289

diff --git a/bin/pycbc_submit_dax b/bin/pycbc_submit_dax
--- a/bin/pycbc_submit_dax
+++ b/bin/pycbc_submit_dax
@@ -163,7 +163,7 @@ while true ; do
         "") shift 2 ;;
         *) LOCAL_PEGASUS_DIR=$2 ; shift 2 ;;
       esac ;;
-    -G|--no-grid) NO_GRID="--forward nogrid" ; shift ;;
+    -G|--no-grid) NO_GRID="--nogrid" ; shift ;;
     -h|--help)
       echo "usage: pycbc_submit_dax [-h] --dax DAX [optional arguments]"
       echo
@@ -266,26 +266,27 @@ else
   fi
 fi
 
-#Check that the proxy is valid
-set +e
-grid-proxy-info -exists
-RESULT=$?
-set -e
-if [ ${RESULT} -eq 0 ] ; then
-  PROXY_TYPE=`grid-proxy-info -type | tr -d ' '`
-  if [ x${PROXY_TYPE} == 'xRFC3820compliantimpersonationproxy' ] ; then
-    grid-proxy-info
+if [ -z ${NO_GRID} ] ; then
+  #Check that the proxy is valid
+  set +e
+  grid-proxy-info -exists
+  RESULT=$?
+  set -e
+  if [ ${RESULT} -eq 0 ] ; then
+    PROXY_TYPE=`grid-proxy-info -type | tr -d ' '`
+    if [ x${PROXY_TYPE} == 'xRFC3820compliantimpersonationproxy' ] ; then
+      grid-proxy-info
+    else
+      cp /tmp/x509up_u`id -u` /tmp/x509up_u`id -u`.orig
+      grid-proxy-init -cert /tmp/x509up_u`id -u`.orig -key /tmp/x509up_u`id -u`.orig
+      rm -f /tmp/x509up_u`id -u`.orig
+      grid-proxy-info
+    fi
   else
-    cp /tmp/x509up_u`id -u` /tmp/x509up_u`id -u`.orig
-    grid-proxy-init -cert /tmp/x509up_u`id -u`.orig -key /tmp/x509up_u`id -u`.orig
-    rm -f /tmp/x509up_u`id -u`.orig
-    grid-proxy-info
+    echo "Error: Could not find a valid grid proxy to submit workflow."
+    exit 1
   fi
-else
-  echo "Error: Could not find a valid grid proxy to submit workflow."
-  exit 1
 fi
-
 
 #Make a directory for the submit files
 SUBMIT_DIR=`mktemp --tmpdir=${LOCAL_PEGASUS_DIR} -d pycbc-tmp.XXXXXXXXXX`
@@ -432,7 +433,8 @@ chmod 755 debug
 echo pegasus-remove $SUBMIT_DIR/work > stop
 chmod 755 stop
 
-cat << EOF > start
+if [ -z ${NO_GRID} ] ; then
+  cat << EOF > start
 #!/bin/bash
 
 if [ -f /tmp/x509up_u\`id -u\` ] ; then
@@ -465,9 +467,9 @@ else
 fi
 
 EOF
+fi
+
 echo pegasus-run $SUBMIT_DIR/work >> start
-
-
 
 chmod 755 start
 
